language: node_js
node_js:
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "n1SnEeab91CIZjugRz83YP9NMf9LN1M4A0X5RVldqU6IqJsXEg+7o3v2ZBMnKFBRasO9Ga7OlmwQ0EGxObOjT9iD0V5OdUwJOLoAb/gyW7dLwZ6e8sVsNpFl2Z1nxu2y5JZ7lqvjKVVFLDfxsqxqmmP0XTCoMaXdYh6lQ1SisEYoyur2TE9MI2mKR6zWXliKE4/Qm0UkaUZXqDnH2xq0Ahw5/y4+/cjr+KruUfmqkeQnFCgseWAiAiOXwSiygpjie6OSRCIbB/SwdYnkVlLYO0tfs1ewJmFWGmRtnzifJ7g+ogcmC2beXSBvAC9YA1lVEPgJ9rmQvX6qY4RD1mA3rDbQKdpHQIp1V4C8+ntfl7rXpmi/lIYsExScZrxCukvvKuFM474D529w1ZzEIE98lZzv1TZQtv2Ar0iHEVqK3PyOqhm5SUXjJ7ORmqCfnqNlrQXLEXwNlZzhcw+7FNUk5L9HIiW8tz3yARwS7LEfz70+/2aeeN9sKaqzmedSw2fmdpNd1ZJJGb5PEd4uoOcE0GrC4WP+blxmvzY3/oS2fv8OfWp3u+uC2rgeBfT0P0U7WLCdmtfxe24keeTtvLHfYI9ow9wdyw7jVOMgmUXJQ+1lEppNUA8C4L63AfAF9wC8aPauzPWi/aqSogyNbmMlTGqwEryAzpYR00O69iU76Eg="